language: python
dist: xenial

notifications:
  email:
    - michele@openquake.org
    - daniele@openquake.org

services:
 - docker

before_install:
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-engine.git ${BRANCH})" == "" ]; then BRANCH='master'; fi; git clone -b ${BRANCH} --depth=1 https://github.com/gem/oq-engine.git && echo "Running on oq-engine/${BRANCH}"
  # Run against the latest docker-compose available
  - pip -q install -U docker-compose

jobs:
  include:
  - stage: celery
    env: SHARED
    install:
      - docker-compose -p oqcluster up -d
    before_script:
      - sleep 30 && docker ps -a
      - docker exec -ti oqcluster_master_1 oq celery status
    script:
      # Set permissions on exported dir
      - docker exec -u 0 -w /io -ti oqcluster_master_1 /bin/bash -c "chown -R 1000 oq-engine"
      - time docker exec -ti oqcluster_master_1 /io/oq-engine/bin/run-demos.sh /io/oq-engine/demos
      - curl http://localhost:8800/v1/calc/list
  - stage: packaging
    env: EXEC
    script:
        - cd oq-engine
        - ./.travis/py_shebangs.sh
        - ./.travis/py_executables.sh
  - stage: packaging
    env: WHL
    script:
        - cd oq-engine
        - ./.travis/packaging.sh
