sudo: required

language: python

notifications:
  email:
    - michele@openquake.org
    - daniele@openquake.org

services:
 - docker

before_install:
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi

install:
  # pip do not cache data when requirements includes full http URLs, so we need to download
  # the wheels first, put the folder in cache and then install the wheels from there.
  # A second run of 'pip download' will download only the missing wheels. 
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-engine.git ${BRANCH})" == "" ]; then BRANCH='master'; fi; git clone -b ${BRANCH} --depth=1 https://github.com/gem/oq-engine.git && echo "Running on oq-engine/${BRANCH}"
  - docker-compose -p oqcluster up -d

before_script:
  - sleep 10 && docker ps -a
  - docker exec -ti oqcluster_master_1 oq celery status

script:
  - docker exec -ti oqcluster_master_1 /io/bin/run-demos.sh
