sudo: required

language: python

python:
 - "3.5"

services:
 - rabbitmq

cache:
  pip: true
  directories:
  - wheels

env:
  - OQ_DISTRIBUTE=celery

jobs:
  include:
  - stage: tests
    env: ENGINE
    before_script:
        - mkdir ~/oqdata
    script:
        - OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.engine
        - OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.server
        - travis_wait 30 OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.calculators
        - OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.risklib
        - OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.commonlib
        - OQ_DISTRIBUTE=celery nosetests --with-doctest -xvs -a'!slow' openquake.commands
  - stage: tests
    env: DEMOS
    script:
        - time bin/run-demos.sh $TRAVIS_BUILD_DIR/oq-engine/demos
        - bin/check_demos

before_install:
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi

install:
  # pip do not cache data when requirements includes full http URLs, so we need to download
  # the wheels first, put the folder in cache and then install the wheels from there.
  # A second run of 'pip download' will download only the missing wheels. 
  - git clone --depth=1 -b $BRANCH https://github.com/gem/oq-engine.git
  - pip -q download -r oq-engine/requirements-py35-linux64.txt -d wheels
  - pip -q install wheels/*
  - pip -q install -e oq-engine
  # Setup RabbitMQ user and hosts
  - sudo rabbitmqctl add_user openquake openquake
  - sudo rabbitmqctl add_vhost openquake
  - sudo rabbitmqctl set_permissions -p openquake openquake ".*" ".*" ".*"
  - sed -i 's/oq_distribute = futures/oq_distribute = celery/g' oq-engine/openquake/engine/openquake.cfg

before_script:
  - cd oq-engine
  - python -c'import platform; print(platform.platform()); import multiprocessing; print("#CPUs=%d" % multiprocessing.cpu_count())'
  - celery worker --purge -Ofair --config openquake.engine.celeryconfig &
  - python utils/celery-status
