version: '2'
services:
  master:
    image: openquake/engine-master-zmq
    volumes:
      - oqdata:/home/openquake/oqdata
      - ./oq-engine:/io/oq-engine
      - ./oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    networks:
      - cluster
    ports:
      - 8800:8800
  worker:
    image: openquake/engine-worker-zmq
    volumes:
      - oqdata:/home/openquake/oqdata:ro
      - ./oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    networks:
      - cluster
    depends_on:
      - master

volumes:
  oqdata:

networks:
  cluster:
