version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=openquake 
      - RABBITMQ_DEFAULT_USER=openquake
      - RABBITMQ_DEFAULT_PASS=openquake
    networks:
      - cluster
  master:
    image: openquake/engine-master
    volumes:
      - oqdata:/home/openquake/oqdata
      - ./oq-engine:/io/oq-engine
      - ./oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    networks:
      - cluster
    ports:
      - 8800:8800
    depends_on:
      - rabbitmq
  worker:
    image: openquake/engine-worker
    volumes:
      - oqdata:/home/openquake/oqdata:ro
      - ./oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    environment:
      - OQ_RABBITMQ_HOST=rabbitmq
    entrypoint: ["./celery-wait.sh"]
    networks:
      - cluster
    depends_on:
      - rabbitmq
      - master

volumes:
  oqdata:

networks:
  cluster:
