version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=openquake 
      - RABBITMQ_DEFAULT_USER=openquake
      - RABBITMQ_DEFAULT_PASS=openquake
    networks:
      - cluster
    # Make sure a proper ulimit is set:
    # erl_child_setup will take forever otherwise
    # see: https://groups.google.com/forum/#!topic/rabbitmq-users/hO06SB-QBqc
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
  master:
    image: openquake/engine-master-celery
    depends_on:
      - rabbitmq
  worker:
    image: openquake/engine-worker-celery
    environment:
      - OQ_RABBITMQ_HOST=rabbitmq
    entrypoint: ["./celery-wait.sh"]
    depends_on:
      - rabbitmq
      - master
