version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=openquake 
      - RABBITMQ_DEFAULT_USER=openquake
      - RABBITMQ_DEFAULT_PASS=openquake
    networks:
      - oqnet
  master:
    image: openquake/engine-master
    volumes:
      - ./oq-engine:/io/oq-engine
      - ./openquake.cfg:/etc/openquake/openquake.cfg
    networks:
      - oqnet
    ports:
      - 8800:8800
    depends_on:
      - rabbitmq
  worker:
    image: openquake/engine-worker
    environment:
      - OQ_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./openquake.cfg:/etc/openquake/openquake.cfg
    entrypoint: ["./celery-wait.sh"]
    networks:
      - oqnet
    depends_on:
      - rabbitmq
      - master

networks:
  oqnet:
